### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by almson** [almson/almson-refcount#3]
As soon as someone comes forward to say that it is useful and that it's working for them, I'll make a release and put it on Maven.

**Comment by vladak** [comment]
Yes please !

**Comment by almson** [comment]
@vladak What? really? are you using it?

**Comment by vladak** [comment]
Well, it is currently used in a feature branch to construct the fix for https://github.com/oracle/opengrok/issues/3361

**Comment by almson** [comment]
@vladak Which branch is it?

**Comment by almson** [comment]
Published
